version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./Back/ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
