version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - "80"

  backend:
    build:
      context: ../Back
      dockerfile: Dockerfile
    expose:
      - "5006"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ../Back/ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
